import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { AuditConfigFullSchema, type AuditConfig } from './schema.js';

export interface LoadConfigOptions {
  configPath?: string;
  overrides?: Partial<Record<string, unknown>>;
}

/**
 * Load and validate an audit configuration from a YAML file.
 * Falls back to CLI overrides when no config file exists.
 */
export function loadConfig(options: LoadConfigOptions = {}): AuditConfig {
  const configPath = options.configPath ?? findConfigFile();

  let raw: Record<string, unknown> = {};

  if (configPath && existsSync(configPath)) {
    const content = readFileSync(configPath, 'utf-8');
    const parsed: unknown = parseYaml(content);
    if (parsed && typeof parsed === 'object') {
      raw = parsed as Record<string, unknown>;
    }
  }

  // Merge CLI overrides
  if (options.overrides) {
    raw = deepMerge(raw, options.overrides);
  }

  const result = AuditConfigFullSchema.safeParse(raw);

  if (!result.success) {
    const errors = result.error.issues
      .map((i) => `  - ${i.path.join('.')}: ${i.message}`)
      .join('\n');
    throw new Error(`Invalid configuration:\n${errors}`);
  }

  return result.data;
}

/**
 * Generate a default config YAML string for `uiux-audit init`.
 */
export function generateDefaultConfig(targetUrl: string): string {
  return `# UI/UX Auditor Configuration
# Generated by uiux-audit init

target:
  url: ${targetUrl}

# repo:
#   path: .

# auth:
#   storageState: ./auth/storageState.json

exploration:
  maxStates: 1000
  maxDepth: 15
  maxActionsPerState: 30
  maxRuntimeMinutes: 60

viewports:
  desktop:
    width: 1440
    height: 900
  tablet:
    width: 768
    height: 1024
  mobile:
    width: 390
    height: 844

audit:
  ui: true
  ux: true
  accessibility: true
  responsive: true
  consistency: true
  console: true

verification:
  enabled: true

ai:
  enabled: false
  # provider: commandcode
  # maxRequests: 200

execution:
  browserWorkers: 2
  aiWorkers: 4

reports:
  markdown: true
  json: true
  html: false
  outputDir: ./uiux-audit-results

# journeys:
#   - name: Example journey
#     goal: Complete a task
#     start: /
`;
}

function findConfigFile(): string | undefined {
  const names = [
    'uiux-audit.config.yaml',
    'uiux-audit.config.yml',
    '.uiux-audit.yaml',
    '.uiux-audit.yml',
  ];

  for (const name of names) {
    const path = resolve(process.cwd(), name);
    if (existsSync(path)) {
      return path;
    }
  }
  return undefined;
}

function deepMerge(
  target: Record<string, unknown>,
  source: Record<string, unknown>
): Record<string, unknown> {
  const result = { ...target };
  for (const key of Object.keys(source)) {
    const sourceVal = source[key];
    const targetVal = target[key];
    if (
      sourceVal &&
      typeof sourceVal === 'object' &&
      !Array.isArray(sourceVal) &&
      targetVal &&
      typeof targetVal === 'object' &&
      !Array.isArray(targetVal)
    ) {
      result[key] = deepMerge(
        targetVal as Record<string, unknown>,
        sourceVal as Record<string, unknown>
      );
    } else if (sourceVal !== undefined) {
      result[key] = sourceVal;
    }
  }
  return result;
}
